#!/bin/bash

# Script to read all files from a tape
# Copyright (C) 2018 John Goerzen <jgoerzen@complete.org>
#
#     This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


set -e

if [ -z "$TAPE" ]; then
    echo "Need to set TAPE, perhaps to /dev/nst0?"
    exit 5
fi

# Might want to set DDOPTS to conv=noerror,sync if there are errors during
# read.

FILENO="${FILENO:=1}"
EMPTIES=0
while [ "$EMPTIES" -lt 4 ] ; do
    FILENAME="`printf "file-%05d.bin" "$FILENO"`"
    if [ -e "$FILENAME" ]; then
        echo "Error: $FILENAME exists"
        exit 5
    fi
    LOGNAME="`printf "file-%03d.log" "$FILENO"`"
    echo " ******** Writing $FILENAME..."
    date
    CSUM="`dd "if=$TAPE" bs=1048576 $DDOPTS 2> >(tee "$LOGNAME" >&2) | mbuffer -m 100M -s 1M | tee "$FILENAME" | sha256sum | awk '{ print $1 }'`" || true
    
    echo "$CSUM  $FILENAME" >> sums
    
    if [ ! -s "$FILENAME" ]; then
        EMPTIES=$(($EMPTIES + 1))
    fi
    FILENO=$(($FILENO + 1))
    date
    sleep 5
done

sync
echo "Found end of tape.  Verifying checksums..."
sha256sum -c sums
